apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hotel-v2
  labels:
    app: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      containers:
      - name: hotel
        image: punix/hotelwebsite:v2
        ports:
        - containerPort: 80